Repository 42-PINTING/FE-PINTING, pull requests merged in 2024-07, with the labels that each got.

#78 feat: 백스페이스 말고도 delete키로 삭제할수 있게 변경
  src/app/painting/_component/_utils/switchTool.tsx
Labels: enhancement

#77 [Feat] dockerfile 생성
  Dockerfile
  Makefile
Labels: good first issue

#82 [bug] makefile 수정
  Makefile
  public/img/test.jpg
Labels: bug

#83 81 feat 되돌리기 기능구현
  src/app/painting/_atoms/canvasAtoms.tsx
  src/app/painting/_component/_utils/switchTool.tsx
  src/app/painting/_component/_utils/textTool.tsx
  src/app/painting/_component/_utils/toolIndex.tsx
  src/app/painting/_component/_utils/undoRedoTool.tsx
  src/app/painting/_component/whiteBoard.tsx
Labels: enhancement

#80 79 feat 텍스트 삽입 할수있게 기능구현
  src/app/painting/_component/_utils/textTool.tsx
  src/app/painting/_component/whiteBoard.tsx
Labels: enhancement

#85 84 feat 펜 굵기와 색상 설정 기능 추가
  src/app/painting/_component/_utils/penTool.tsx
  src/app/painting/_component/_utils/switchTool.tsx
  src/app/painting/_component/_utils/toolIndex.tsx
Labels: enhancement

#91 89 feat 직선 굵기 색상변경 가능하게 변경
  src/app/painting/_component/_utils/lineTool.tsx
  src/app/painting/_component/_utils/switchTool.tsx
  src/app/painting/_component/_utils/toolIndex.tsx
Labels: enhancement

#90 88 feat 직선 기능 구현
  src/app/painting/_component/_utils/lineTool.tsx
Labels: enhancement
